services:
  db:
    container_name: tasked-db
    image: postgres:17.0
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tadmin
      POSTGRES_PASSWORD: troot
      POSTGRES_DB: tasked-db
    networks:
      - tasked-net
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tadmin -d tasked-db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    container_name: tasked-backend
    build: backend
    ports:
      - "8000:8000"
    networks:
      - tasked-net
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: tasked-frontend
    build: frontend
    ports:
      - "80:5173"
    networks:
      - tasked-net

  test:
    container_name: pytest
    image: python:3.13.2-alpine3.21
    networks:
      - tasked-net
    depends_on:
      - backend
    volumes:
      - ./backend:/backend
    command: sh -c "pip install --no-cache-dir -r /backend/requirements.txt && pip install --no-cache-dir pytest && pytest /backend/test.py"

networks:
  tasked-net:
    driver: bridge

volumes:
  db-data:
    driver: local